### ISSUE TITLE
Getting ThrowAddingDuplicateWithKeyArgumentException when using RadListView

### ISSUE THREAD

**Issue by AAleksiev** [telerik/UI-For-UWP#48]
I'm getting ThrowAddingDuplicateWithKeyArgumentException when using RadListView. I've attached is sample app so hopefully this will help you identify the issue.

at System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException(Object key)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Telerik.UI.Xaml.Controls.Data.ListView.Model.BaseLayoutStrategy.RecycleLocally()
   at Telerik.UI.Xaml.Controls.Data.ListView.Model.BaseLayoutStrategy.MeasureContent(RadSize availableSize, Double offset, Double bufferScale)
   at Telerik.UI.Xaml.Controls.Data.ListView.Model.LayoutController.MeasureContent(RadSize newAvailableSize)
   at Telerik.UI.Xaml.Controls.Data.ListViewModel.MeasureContent(RadSize newAvailableSize)
   at Telerik.UI.Xaml.Controls.Data.RadListView.OnContentPanelMeasure(RadSize newAvailableSize)
   at Telerik.UI.Xaml.Controls.Data.ListView.ListViewPanel.MeasureOverride(Size availableSize)

[TelericUiControls.zip](https://github.com/telerik/UI-For-UWP/files/839230/TelericUiControls.zip)

**Comment by AAleksiev** [comment]
I've realised where the issue is. It's with my test case as I use one instance of my view model for all listview items.

**Comment by APopatanasov** [comment]
Hi @AAleksiev , 
I am glad to here that you were able to find the cause for your issue and now everything is working as expected you you. 

Indeed using the same instance for the items throws the observed ThrowAddingDuplicateWithKeyArgumentException. Thank you for sharing with us your observations. 🥇 

If you have any other concerns, please let us know. 😄
