### ISSUE TITLE
TargetParameterCountException when binding ItemsSource with x:Bind expression

### ISSUE THREAD

**Issue by schnitty** [telerik/UI-For-UWP#84]
When I try to bind the ItemsSource property of the RadDataGrid with an x:Bind expression

`<Grid:RadDataGrid ItemsSource="{x:Bind ViewModel.Items}"></Grid:RadDataGrid>`

I get the following exception:

TargetParameterCountException: Parameter count mismatch.
StackTrace
 at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at Telerik.Data.Core.BindingExpressionHelper.<>c__DisplayClass0_0.<CreateGetValueFunc>b__0(Object item)
   at Telerik.Data.Core.Fields.PropertyInfoFieldInfo.GetValue(Object item)
   at Telerik.UI.Xaml.Controls.Grid.DataGridTypedColumn.GetValueForInstance(Object instance)
   at Telerik.UI.Xaml.Controls.Grid.Model.GridModel.Telerik.UI.Xaml.Controls.Grid.ITable.GetCellValue(ItemInfo rowItemInfo, ItemInfo columnItemInfo)
   at Telerik.UI.Xaml.Controls.Grid.CellsController`1.GetCellDecorator(IItemInfoNode parentRow, ItemInfo columnItemInfo, Int32 rowLine, Int32 columnLine)
   at Telerik.UI.Xaml.Controls.Grid.CellsController`1.GenerateCellsForRow(IItemInfoNode rowDecorator, Int32 rowSlot)
   at Telerik.UI.Xaml.Controls.Grid.Model.GridModel.GenerateCellsForReadOnlyRow(Int32 rowSlot, Double largestRowElementWidth, IItemInfoNode rowDecorator)
   at Telerik.UI.Xaml.Controls.Grid.Model.GridModel.Telerik.UI.Xaml.Controls.Grid.ITable.GenerateCellsForRow(Int32 rowSlot, Double largestRowElementHeight, IItemInfoNode rowDecorator)
   at Telerik.UI.Xaml.Controls.Grid.NodePool`2.GenerateCellsForLine(Int32 slot, Double largestLength, T lastElement)
   at Telerik.UI.Xaml.Controls.Grid.NodePool`2.GenerateContainer(IList`1 itemInfos)
   at Telerik.UI.Xaml.Controls.Grid.NodePool`2.MeasureForward(MeasureContext& context)
   at Telerik.UI.Xaml.Controls.Grid.NodePool`2.MeasureVertically(RadSize availableSize, Double offset, Double bufferScale)
   at Telerik.UI.Xaml.Controls.Grid.NodePool`2.OnMeasure(RadSize availableSize, Double offset, Int32 frozenElementsCount, Double verticalBufferScale)
   at Telerik.UI.Xaml.Controls.Grid.Model.GridModel.MeasureCells(RadSize newAvailableSize)
   at Telerik.UI.Xaml.Controls.Grid.RadDataGrid.OnCellsPanelMeasure(RadSize newAvailableSize)
   at Telerik.UI.Xaml.Controls.Grid.Primitives.DataGridCellsPanel.MeasureOverride(Size availableSize)
   at Windows.UI.Xaml.UIElement.UpdateLayout()
   at Microsoft.VisualStudio.DesignTools.UwpDesigner.Views.ViewObjects.WindowsUIXamlViewVisual.UpdateLayout()
   at Microsoft.VisualStudio.DesignTools.UwpDesigner.Views.WindowsXamlSceneView.UpdateLayoutInternal()
   at Microsoft.VisualStudio.DesignTools.Designer.Views.SceneView.UpdateLayout()

InnerException: None

When I bind with a standard binding

`<Grid:RadDataGrid ItemsSource="{Binding Items}"></Grid:RadDataGrid>`

It binds correctly.

**Comment by mvegaca** [comment]
I've the same Issue using this control on Windows Template Studio page template:

[Grid page throwing TargetParameterCountException in VS designer
](https://github.com/Microsoft/WindowsTemplateStudio/issues/496)

It works if I use Binding instead of x:Bind

Thanks

**Comment by APopatanasov** [comment]
Hi @mvegaca ,
We will apply a fix for this issue in the next few days in order to prevent the designer from crushing when x:Bind is used.

**Comment by crutkas** [comment]
We can expect a fix via nuget in the next few days?

**Comment by APopatanasov** [comment]
Hi @crutkas ,
We will upload a new version of the nuget package in the next few days. 😊

**Comment by crutkas** [comment]
@APopatanasov awesome, thanks for the status update and quick fix

**Comment by APopatanasov** [comment]
@crutkas A [new version](https://www.nuget.org/packages/Telerik.UI.for.UniversalWindowsPlatform/1.0.0.4) of the package has been uploaded.
